apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uo0w7ns9z-java-quarkus
  janus-idp.io/tekton: uo0w7ns9z-java-quarkus
  backstage.io/kubernetes-id: uo0w7ns9z-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uo0w7ns9z-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
